api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "ciwi-bundle-order-discount-function"
type = "function"
uid = "3dfee65d-f9a6-6dd6-37e5-f13423d290cf6d229b2f"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
