api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "ciwi-bundle-free-shipping-discount-function"
type = "function"
uid = "8bdd0087-99d5-7553-9ad3-48bdcc06b48d2ffcb7d2"
description = "t:description"

[[extensions.targeting]]
target = "cart.delivery-options.discounts.generate.run"
input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
export = "cart-delivery-options-discounts-generate-run"

[extensions.build]
command = ""
path = "dist/function.wasm"
