# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c39cadd79559cb62c51564f1a572632f"
name = "Ciwi.ai:Bundle(LocalW)"
application_url = "https://2c971c469ed8.ngrok.app"
embedded = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app_subscriptions/update",
  "app_purchases_one_time/update",
  "app/uninstalled"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_products"

[auth]
redirect_urls = [
  "https://2c971c469ed8.ngrok.app/auth/callback",
  "https://2c971c469ed8.ngrok.app/auth/shopify/callback",
  "https://2c971c469ed8.ngrok.app/api/auth/callback"
]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
