# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b896c10abe3ca220b1efbc333ef41ad1"
name = "Ciwi.ai: Image & Alt Translate"
handle = "ciwi-image-translation"
application_url = "https://translateimageprod.onrender.com"
embedded = true

[build]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_metaobjects,read_online_store_navigation,unauthenticated_read_product_listings,read_themes,read_translations,unauthenticated_read_metaobjects,write_locales,write_markets,write_metaobjects,write_products,write_translations"
optional_scopes = ["read_customer_events","write_pixels"]
[auth]
redirect_urls = [
  "https://translateimageprod.onrender.com/auth/callback",
  "https://translateimageprod.onrender.com/auth/shopify/callback",
  "https://translateimageprod.onrender.com/api/auth/callback"
]
  
[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [
  "app_purchases_one_time/update",
  "app_subscriptions/update",
  "app/uninstalled"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
