# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7fe2398f1feb814e87fb51ac1364bb9"
name = "Ciwi.ai: Image & Alt (local)"
handle = "translate-image-local"
application_url = "https://church-begun-counted-eau.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0f992326.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_legal_policies,read_metaobjects,read_online_store_navigation,unauthenticated_read_product_listings,read_themes,read_translations,unauthenticated_read_metaobjects,write_locales,write_markets,write_metaobjects,write_products,write_translations,write_files,write_themes"
[auth]
redirect_urls = [
  "https://church-begun-counted-eau.trycloudflare.com/auth/callback",
  "https://church-begun-counted-eau.trycloudflare.com/auth/shopify/callback",
  "https://church-begun-counted-eau.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [
  "app_purchases_one_time/update",
  "app_subscriptions/update",
  "app/uninstalled"
]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

